# Project configs
project_id = "rsgdmshodeqrgoqnfjvh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
name = "create-checkout-session"
verify_jwt = true

[[functions]]
name = "manage-payment-methods"
verify_jwt = true

[[functions]]
name = "stripe-webhook"
verify_jwt = false

[[functions]]
name = "update-stripe-keys"
verify_jwt = true