# Project configs
project_id = "rsgdmshodeqrgoqnfjvh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Function configs
[[functions]]
verify_jwt = true
name = "create-checkout-session"

[[functions]]
verify_jwt = true
name = "manage-payment-methods"

[[functions]]
verify_jwt = false
name = "stripe-webhook"